# Generated by Django 3.2.2 on 2021-09-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracoes',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='atracoes'),
        ),
    ]
