# Generated by Django 3.2.2 on 2021-10-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0002_atracoes_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracoes',
            name='observacoes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
